
title: Berk Köprücü
email: info@berksoftware.com
author: 'Berk Köprücü'
copyright: "(c) {currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
  Berk Köprücü Berk Koprucu - Software Engineer, Beckend, Java, Kotlin, Spring Boot, System Design, Software Architecture, Backend, Cloud Computing, Kubernetes, AWS
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jekyll4test.pages.dev/" # the base hostname & protocol for your site, e.g. http://example.com
# favicon: "/favicon.png"
favicon: "/favicon.svg"

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: jekyll-theme-clean-blog
theme: jekyll-theme-yat

#sitemap: true
header_pages:
  - index.html
  - about.html
  - categories.html
  - tags.html
  - archives.html

yat:
  date_format: "%b %d, %Y"

# header_transparent: true

brandimage_enabled: false # Logo image on header bar

timezone: Europe/Stockholm

debug: false

paginate: 3

# Custom color as below:
# theme_color: "#882250"

# night_mode: "auto"


google_analytics: false
# Google analytics - GA4
# google_analytics: [Measurement ID]
# enableDNT: "false"

# If you want to generate website sitemap, you can set true
# sitemap: false

seo_enabled: false

excerpt_size: 350
badge_new_enabled: false

markdown: kramdown


# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   image: null             # Image banner source
#   opacity: 1.0            # Banner opacity (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   height: "640px"         # Banner default height
#   min_height: null        # Banner minimum height
#   heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # Custom subheading style (e.g. color: gold)

# Excerpt settings
# excerpt:
#   image_style: z          # Image layout style (It's value could be none, left, right, top, z, z-reverse)
#   image_width: 38.2%      # Image default width
#   image_height: 160px     # Image default height
#   text_size: 350          # Words default size

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Utterances comments
# See https://utteranc.es/
# set follow_site_theme true to make utterances' theme follow the site's

# utterances:
#   repo: "owner/repo"
#   issue_term: "title"
#   label: "utterances comment"
#   theme: "github-light"
#   follow_site_theme: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

defaults:
  - scope:
      path: ""
    values:
      layout: "post"


exclude:
  - LICENSE
  - README.md
  - .idea/
  - .gitignore
  - .github/

