# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Your awesome title'
subtitle: 'Subtitle is here'
masthead_title: 'Masthead title'
name: 'Site Name'
email: your-email@example.com
author: Berk
copyright: "Unpublished Work (cleft) 2023-{currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: ""


paginate: 10
paginate_path: /page:num/
timezone: Europe/Stockholm
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
search: true

#markdown: kramdown
#kmarkdown:
#  input: GFM
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  # - jemoji
  # - jekyll-seo-tag
  # - jekyll-spaceship

author:
  name   : "Berk Köprücü"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Senior Software Engineer, with more than 15 years experience on Java platform."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://berkkoprucu.com"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bkoprucu"
    # - label: "LinkedIn"
    #   icon: "fab fa-fw fa-linkedin"
    #   url: "https://www.linkedin.com/in/koprucu/"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:bkoprucu@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bkoprucu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/koprucu/"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@marchoftime"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://www.stackoverflow.com/koprucu/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/      




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
