# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Berk Köprücü
email: info@berkkoprucu.com
author: 'Berk Köprücü'
copyright: "(c) {currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
  Berk Köprücü - Software Engineer, Java, Spring Boot, 
  System Design, Software Architecture, Backend, Cloud Computing, Kubernetes, AWS
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jekyll4test.pages.dev/" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/favicon.png"

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: jekyll-theme-clean-blog
theme: jekyll-theme-yat

#sitemap: true
header_pages:
  - index.html
  - categories.html
  - tags.html
  - about.md

yat:
  date_format: "%b %d, %Y"

timezone: Europe/Stockholm

debug: true

paginate: 6
google_analytics: false
seo_enabled: false

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

defaults:
  - scope:
      path: ""
    values:
      layout: "post"


exclude:
  - LICENSE
  - README.md
  - .idea/
  - .gitignore
  - .github/

